require("plugins.config.onedark")
require("plugins.config.lualine")
require("plugins.config.telescope")
require("plugins.config.nvim-tree")
require("plugins.config.nvim-treesitter")
require("plugins.config.lsp")
require("plugins.config.none-ls")
require("plugins.config.alpha")
